### ISSUE TITLE
Two bugs when creating barcharts

### ISSUE THREAD

**Issue by PZonneveld** [mendix/ChartJS#67] opened 2016-03-14 15:37 UTC
Hi,

Currently I am working on a Mendix project and am using the ChartJS plugin to create barcharts within my application. While using the plugin I have encountered two bugs which are now holding up my project.  

The first bug is triggerd when ChartJS receives the datapoints objects when they are empty. This seems to trigger an enless loop in which I cannot enter the desired page and thus cannot view the graphs. 
The second bug is that the barchart seems to ignore the option to start at zero. Whether the box is checked or not in the properties, the barchart never starts at zero.

Any help how to resolve these issues would be much appreciated!

**Comment by JelteMX** [comment] 2016-04-08 09:10
I cannot reproduce either of those issues. If you can send a testproject to community [at] mendix.com I would be glad to help. I did do another fix (["Fix rendering for empty datasets"](https://github.com/mendix/ChartJS/commit/413a34bc3d12a2711c570d44f1cf6f69f86f2027)) which makes sure that empty datasets are ignored

**Comment by JelteMX** [comment] 2016-04-08 11:01
Correction.... I have reproduced the start at zero issue. Fix is coming

**Comment by JelteMX** [comment] 2016-04-11 07:40
Both issues are fixed according to the feedback. Closing the issue

**Closed as completed by JelteMX** 2016-04-11 07:40 UTC
