### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by rickyv3** [mendix/ChartJS#92] opened 2016-11-16 22:00 UTC
Hello,

It appears a recent version of the widget results in a large memory leak. As I am sure you can imagine, that has caused all sorts of performance related issues for us. We utilize temporary objects in conjunction with this widget, but it seems that the temporary objects are not actually temporary. 

I've attached a couple screenshots to show you what we are seeing within our app. We have also brought this up to Mx and they confirmed our suspicion, that the chartjs widget is causing a memory leak. Our contact at Mx was sure this is only fixable within the widget itself.

Can you take a look?

![objectcache](https://cloud.githubusercontent.com/assets/13573078/20367541/904e983e-ac15-11e6-8897-880653bec72c.png)

![objectcount](https://cloud.githubusercontent.com/assets/13573078/20367569/b7003e06-ac15-11e6-892d-918092386fb0.png)

**Comment by JelteMX** [comment] 2016-11-21 10:52
Could you test [this version](https://github.com/mendix/ChartJS/raw/fix/memoryleak/test/widgets/ChartJS.mpk)? This should fix the problem, although I still have to look into the DataPoints, not sure if those are released as well

**Comment by JelteMX** [comment] 2016-11-21 11:12
Update: Same link now links to version that will also release datapoints if they are there. It uses [https://apidocs.mendix.com/6/client/mx.data.html](mx.data.release) and is done in [uninitialize](https://github.com/mendix/ChartJS/blob/fix/memoryleak/src/ChartJS/widgets/Core.js#L223).

It checks if ``mx.data.release`` is available, as this will be deprecated in Mendix 7

**Comment by rickyv3** [comment] 2016-11-22 14:24
Hi Jelte,

We've given the fix a try, and it seems we have only part of the solution. The cache is cleared when the user signs out of the app, which is good, but it is not cleared when they leave the page. We believe the datapoints, datasets and chart objects should be cleared when the user leaves the page where they generated said charts.

**Comment by JelteMX** [comment] 2016-11-22 15:52
What do you mean with 'cleared'? As in, this should be cleared in the backend? If that's the case, this should be fixed by my fix, using ``mx.data.release``. On the front-end these values do not remain, as they are part of the widget (and thus destroyed).

If it is indeed back-end, we have to check it with R&D, because this is the only viable solution that I can think of.

**Comment by JelteMX** [comment] 2016-11-23 09:10
Got some other feedback that this doesn't solve the issue yet (keeping objects in the cache), which seems strange. Next thing I am going to try is doing a ``mx.data.release`` when ChartJS has plotted or on a refresh

**Comment by rickyv3** [comment] 2017-02-16 15:12
Has this been addressed? It doesn't look like it has been resolved on our end.

**Comment by rickyv3** [comment] 2017-05-03 17:50
Hi Jelte - anything new to report here? We are running into big issues.

**Comment by JelteMX** [comment] 2017-05-10 08:58
Well I still haven't found out what the problem is. We are releasing all objects in the widget, I double checked. This might be an issue R&D has to investigate, because I'm running out of options here

**Comment by JelteMX** [comment] 2017-05-10 15:38
I did some intensive investigation and I conclude that this is not an issue with the widget itself. Yes, objects weren't released in previous versions of the widget, which is bad practice, so it seems. That's why we introduce ``mx.data.release`` in the ``uninitialize`` method. (per release [3.5.3](https://github.com/mendix/ChartJS/releases/tag/v3.5.3))

Did this solve the problem in the test-project (GC-Test on Sprintr)? No. This was created in Mendix 5.21.5. I checked the issue in our own test-project and objects were kept in the cache.

But, then I decided to open our test-project in Mx 6.4.1. The non-persistent objects are not kept in cache when `mx.data.release` is called. Therefore , the problem is not in the widget itself, but in the MX runtime.

To solve the problem, the options are limited:

- Update to Mendix 6

That's all I can say about this issue. I know this will not solve the problem in Mendix 5, but that's not something I can do. What I will do is this: introduce an ``onDestroy`` microflow in the widget. This one will be called when the widget is destroyed and will use the dataset object as input parameter. This way you could delete the object yourself (which should not be necessary, but in this case I think it's the only viable solution to this problem).

**Comment by JelteMX** [comment] 2017-05-10 16:47
Suggestion added to [3.6.0](https://github.com/mendix/ChartJS/releases/tag/v3.6.0)

**Closed as completed by JelteMX** 2017-05-10 16:47 UTC

**Comment by rickyv3** [comment] 2017-05-10 17:28
We are using Mx 6.10.3, and the issue persists.

**Comment by JelteMX** [comment] 2017-05-10 19:57
Every object that gets into the widget, is released upon ``uninitialize``. The backend knows we don't need the objects anymore. In my test-project the issue was resolved, which would mean that this issue has nothing to do with the widget, but with the model in your project.

**Comment by JelteMX** [comment] 2017-05-10 20:02
Out of curiosity, two things you could try (might not make sense, but could help):

- Use the newly added ``onDestroy`` microflow under ``behavior``, remove the non-persistent chart entity. This should mean that the other objects can be destroyed, as they have no reference anymore
- Set delete behavior on the non-persistent reference. Like I said, doesn't make sense, since they are non-persistent, but I'd like to know if that might help.

As far as I know I have everything covered in the widget to release the objects. This would mean that there is something else wrong with the logic in your project. Contact Support, I think we'll need access to the project to see where the problem occurs. It can't be this widget, because the issue was resolved in our own test-project.
