### ISSUE TITLE
Issue w/ 5.12

### ISSUE THREAD

**Issue by rickyv3** [mendix/ChartJS#59] opened 2016-01-22 21:38 UTC
I just tried to import / update the JSChart .mpk I have in my project in version 5.12, and received the following error:

Any idea what caused this or what I can do to fix it?

Thanks
## 

Package 'C:\Users\rickyv3\Documents\Kinetech PM Interiors-main_2\widgets\ChartJS.mpk': Widget XML file 'ChartJS/widgets/BarChart/BarChart.xml' does not conform to the XML schema:

The 'name' attribute is invalid - The value 'Decimal' is invalid according to its datatype 'http://www.mendix.com/widget/1.0/:attributeTypeNameType' - The Enumeration constraint failed.

The 'name' attribute is invalid - The value 'Decimal' is invalid according to its datatype 'http://www.mendix.com/widget/1.0/:attributeTypeNameType' - The Enumeration constraint failed.

**Comment by JelteMX** [comment] 2016-01-25 12:14
This is due to incompatibilities with this version. In the newer Mendix versions (I'll check, it should be since 5.18) we have dropped the datatypes 'Currency' and 'Float', these are replaced by 'Decimal'. Your Mendix version will not be able to use this new type of datatype, and so it seems to give you an error.

I'll see if I can create a Mendix 5.12 compatible release for this (hopefully this week), in the meantime you can only use the older versions (< v3.0.0)

**Comment by rickyv3** [comment] 2016-01-25 15:17
Thank you! That would be greatly appreciated and very helpful.

**Comment by JelteMX** [comment] 2016-01-26 12:31
Can you check this version for me please? https://github.com/mendix/ChartJS/raw/pre-mx6/test/widgets/ChartJS.mpk

Unfortunately we cannot release different versions for different MX versions right now. I will probably mention this version in the next release on the AppStore, so everybody can enjoy the latest version of this widget for pre-mx6 modeler versions as well

**Comment by rickyv3** [comment] 2016-01-26 13:49
I was able to successfully import the package you provided, update my widgets and then run the project. Unfortunately, only 2 of my charts actually generate within the app (both of which are normal bar charts, but even these are not generating everywhere). All charts I generate are within forms that contain multiple widgets / charts, each within its group box.

I tried clearing my cache, but that did not do the trick.

Any idea what may be causing the issue? Let me know if you have any questions.

Thank you

**Comment by rickyv3** [comment] 2016-02-01 18:07
Hi JelteMx,

Any luck diagnosing the problem here?

Thank you,

**Comment by JelteMX** [comment] 2016-02-02 10:27
Ricky, could you send me a test-project to community [at] mendix.com? I'll see if I can reproduce the problem and check what is wrong. Please mention the link to this issue. I hope to be able to fix this next week at the latest, hopefully earlier

**Comment by JelteMX** [comment] 2016-02-16 11:59
As stated in earlier comment, this is fixed in a pre-mx6 branch. We're referring to: https://github.com/mendix/ChartJS/raw/pre-mx6/test/widgets/ChartJS.mpk

Closing the issue

**Closed as completed by JelteMX** 2016-02-16 11:59 UTC
